-- Server entry point: requires all modules in dependency order.
-- JS files and @oxmysql are loaded via fxmanifest before this file.
-- Config and ox_lib are loaded via shared_scripts.

require 'server.modules.database'
require 'server.main'
require 'server.modules.hooks'
require 'server.modules.phone'
require 'server.modules.contacts'
require 'server.modules.security'
require 'server.modules._utils'
require 'server.modules.notifications'
require 'server.modules.messages'
require 'server.modules.mail'
require 'server.modules.calls'
require 'server.modules.flashlight'
require 'server.modules.nearby_voice'
require 'server.modules.gallery'
require 'server.modules.bank'
require 'server.modules.wallet'
require 'server.modules.documents'
require 'server.modules.documents_fix'
require 'server.modules.chirp'
require 'server.modules.snap'
require 'server.modules.social'
require 'server.modules.garage'
require 'server.modules.yellowpages'
require 'server.modules.matchmylove'
require 'server.modules.services'
require 'server.modules.news'
require 'server.modules.clips'
require 'server.modules.live'
require 'server.modules.proximity'
require 'server.modules.external'
require 'server.modules.storage'
require 'server.modules.livekit'
require 'server.modules.socket'
require 'server.modules.location_tracking'
require 'server.modules.phone_drop'
require 'server.modules.music'
require 'server.modules.notes'
require 'server.modules.retention'
require 'server.modules.darkrooms'
require 'server.modules.radio'
require 'server.modules.cityride'
require 'server.modules.sdk'
