-- Automatically generated by Renewed Audio Tool
fx_version 'cerulean'
game 'gta5'
lua54 'yes'

name 'Renewed Audio Tool'
author 'Renewed Scripts | FjamZoo'
repository 'https://github.com/Renewed-Scripts/Renewed-Audiotool'
contributors 'Ehbw, CodeWalker, ChatDisabled, uShifty'
version '1.0'

files {
    'data/gcphone_sounds.dat54.rel',
    'audiodirectory/sounds.awc'
}

data_file 'AUDIO_WAVEPACK'  'audiodirectory'
data_file 'AUDIO_SOUNDDATA' 'data/gcphone_sounds.dat'

client_script 'client/main.lua'

